version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - database
    environment:
      - FLASK_ENV=production

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password_here
      - MYSQL_DATABASE=intellifarma
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Mount Nginx configuration files
      - ./nginx/certs:/etc/nginx/certs  # Mount SSL certificates

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email your_email@example.com --agree-tos --no-eff-email -d your_domain.com

volumes:
  mysql_data:
  # Add other volumes here as necessary.
