version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map Flask app port to host
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_HOST=localhost
      - DB_NAME=intellifarma
      # Add other environment variables as needed
    depends_on:
      - database

  database:
    image: mysql:latest  # Use the appropriate database image
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password_here
      - MYSQL_DATABASE=intellifarma
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=smartfarming101@gmail.com
      - MAIL_PASSWORD=ltfd jmge jrum hdox
      - MAIL_USE_TLS=true  # or 'false' depending on your setup
      - MAIL_USE_SSL=false
    ports:
      - "3306:3306"  # Map database port to host
