"""hasing passwords

Revision ID: 144e8d453127
Revises: 62f1a844deba
Create Date: 2023-11-16 19:02:20.277081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144e8d453127'
down_revision = '62f1a844deba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
