""" Added logout timestamp

Revision ID: a4389dda5a54
Revises: f3da706ce228
Create Date: 2023-11-26 13:28:26.658783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4389dda5a54'
down_revision = 'f3da706ce228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logout_timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('logout_timestamp')

    # ### end Alembic commands ###
